import "./globals.css";

import type { Metadata } from "next";

import { BackgroundGradient } from "@/components/ui/background-gradient";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModeToggle } from "@/components/ui/mode-toggle";

import { fonts } from "@/config/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fonts.geistSans.variable} ${fonts.geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BackgroundGradient variant="gray">
            <ModeToggle />
            {children}
          </BackgroundGradient>
        </ThemeProvider>
      </body>
    </html>
  );
}
